//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainerDemoEntities : DbContext
    {
        public TrainerDemoEntities()
            : base("name=TrainerDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TrainerMaster> TrainerMasters { get; set; }
        public virtual DbSet<TrainerSkillsDetail> TrainerSkillsDetails { get; set; }
        public virtual DbSet<TrainerTrainingDetail> TrainerTrainingDetails { get; set; }
        public virtual DbSet<TrainerWorkDetail> TrainerWorkDetails { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<TrainerEdnDetail> TrainerEdnDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrainerPersonalDetail> TrainerPersonalDetails { get; set; }
    }
}
