//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerEdnDetail
    {
        public int TrainerEdnId { get; set; }
        public string Course { get; set; }
        public string Institution { get; set; }
        public Nullable<int> FromMonth { get; set; }
        public Nullable<int> FromYear { get; set; }
        public Nullable<int> ToMonth { get; set; }
        public Nullable<int> ToYear { get; set; }
        public string Grade { get; set; }
        public Nullable<int> TrainerId { get; set; }
    }
}
