//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerSkillsDetail
    {
        public int TrainerSkillsId { get; set; }
        public string SkillOne { get; set; }
        public string SkillTwo { get; set; }
        public string SkillThree { get; set; }
        public string DomainOne { get; set; }
        public string DomainTwo { get; set; }
        public string DomainThree { get; set; }
        public string LanguagesOne { get; set; }
        public string LanguagesTwo { get; set; }
        public string LanguagesThree { get; set; }
        public string Description { get; set; }
        public string ProjectOne { get; set; }
        public string ProjectTwo { get; set; }
        public string ProjectThree { get; set; }
        public string TrainerPhotoUrl { get; set; }
        public string TrainerProfileUrl { get; set; }
        public Nullable<int> TrainerId { get; set; }
    }
}
